version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

workflows:
  deploy:
    jobs:
      - heroku/deploy-via-git
      - notify_slack

jobs:
  notify_slack:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
