version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3
  slack: circleci/slack@4.1.1

workflows:
  heroku_deploy:
    jobs:
      - deploy

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
