version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3
  slack: circleci/slack@4.1.1

workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - slack/notify:
                event: pass
                template: success_tagged_deploy_1
