version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3
  node: circleci/node@4.1.0
  slack: circleci/slack@4.1.1

workflows:
  test_and_deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          requires:
            - node/test
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - slack/notify:
                event: pass
                template: success_tagged_deploy_1
